# Generated by Django 4.1.5 on 2023-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkateboardAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='accessories_images/')),
                ('skateboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skateboard')),
            ],
        ),
        migrations.DeleteModel(
            name='SkateboardHardware',
        ),
    ]
